ARG ALPINE_VERSION=latest


# builder
FROM alpine:${ALPINE_VERSION} AS builder
ARG TERRAFORM_DOCS_VERSION=latest
ARG TERRAFORM_VERSION=latest
ARG TERRAGRUNT_VERSION=latest
ARG TFGET_VERSION=latest
ARG TFLINT_VERSION=latest
ARG TFSEC_VERSION=latest
COPY dotfiles/. /root/
ENV CURL='curl -fsSL --netrc-optional'
RUN apk add --update --no-cache \
    bash \
    ca-certificates \
    curl \
    jq \
    unzip

# terraform
RUN /bin/bash -c 'if [[ "${TFGET_VERSION}" == "latest" ]]; then TFGET_VERSION=$(${CURL} "https://api.github.com/repos/hansohn/tfget/releases/latest" | jq -r .tag_name  | sed -e "s:^v::"); fi \
      && ${CURL} https://github.com/hansohn/tfget/releases/download/${TFGET_VERSION}/tfget-${TFGET_VERSION}.tar.gz -o tfget-${TFGET_VERSION}.tar.gz \
      && tar -xzf tfget-${TFGET_VERSION}.tar.gz \
      && mv tfget /usr/local/bin/ \
      && chmod +x /usr/local/bin/tfget \
      && tfget ${TERRAFORM_VERSION} \
      && terraform --version'

# terragrunt
RUN /bin/bash -c 'if [[ "${TERRAGRUNT_VERSION}" == "latest" ]]; then TERRAGRUNT_VERSION=$(${CURL} "https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest" | jq -r .tag_name); fi \
      && ${CURL} https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt \
      && chmod +x /usr/local/bin/terragrunt \
      && terragrunt --version'

# terraform-docs
RUN /bin/bash -c 'if [[ "${TERRAFORM_DOCS_VERSION}" == "latest" ]]; then TERRAFORM_DOCS_VERSION=$(${CURL} "https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest" | jq -r .tag_name); fi \
      && ${CURL} https://github.com/terraform-docs/terraform-docs/releases/download/${TERRAFORM_DOCS_VERSION}/terraform-docs-${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz -o terraform-docs.tar.gz \
      && tar -xzf terraform-docs.tar.gz \
      && mv terraform-docs /usr/local/bin/ \
      && chown root:root /usr/local/bin/terraform-docs \
      && chmod +x /usr/local/bin/terraform-docs \
      && terraform-docs --version'

# tflint
RUN /bin/bash -c 'if [[ "${TFLINT_VERSION}" == "latest" ]]; then TFLINT_VERSION=$(${CURL} "https://api.github.com/repos/terraform-linters/tflint/releases/latest" | jq -r .tag_name); fi \
      && ${CURL} https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip -o tflint.zip \
      && unzip tflint.zip \
      && mv tflint /usr/local/bin/ \
      && chmod +x /usr/local/bin/tflint \
      && tflint --version \
      && tflint --init'

# tfsec
RUN /bin/bash -c 'if [[ "${TFSEC_VERSION}" == "latest" ]]; then TFSEC_VERSION=$(${CURL} "https://api.github.com/repos/aquasecurity/tfsec/releases/latest" | jq -r .tag_name); fi \
      && ${CURL} https://github.com/aquasecurity/tfsec/releases/download/${TFSEC_VERSION}/tfsec-linux-amd64 -o /usr/local/bin/tfsec \
      && chmod +x /usr/local/bin/tfsec \
      && tfsec --version'


# main
FROM alpine:${ALPINE_VERSION} as main
RUN apk add --update --no-cache \
    bash \
    ca-certificates \
    curl \
    jq \
    unzip \
    vim
COPY --from=builder /root/.terraform.d/. /root/.terraform.d/
COPY --from=builder /usr/local/bin/ /usr/local/bin/
RUN /bin/bash -c 'terraform --version'

ENTRYPOINT []
